### ISSUE TITLE
What about the cats??

### ISSUE THREAD

**Issue by JaysonDeMarchi** [lindsaydemarchi/Budget#3]
I don't see a budget for the cats.

Is that included in utilities? 
https://github.com/lindsaydemarchi/Budget/blob/master/better_budget.py#L52

I don't think we want them to go starving.

**Comment by lindsaydemarchi** [comment]
They are considered in a separate CSV not uploaded. The keywords for this CSV also have not been integrated.

**Comment by JaysonDeMarchi** [comment]
good.
